[project]
name = "lf-tracking"
version = "0.1.0"
description = "Real-time drone tracking with MixFormerV2 and CSRT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "easydict>=1.13",
    "einops>=0.8.1",
    "opencv-contrib-python>=4.12.0.88",
    "timm>=1.0.24",
]
